/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
        
import React, { useRef } from 'react'
import { useGLTF, 

 } from '@react-three/drei'


export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/cauldron/model.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
<mesh geometry={nodes.Sphere015.geometry} material={materials['Black.005']} />
<mesh geometry={nodes.Sphere015_1.geometry} material={materials.GreenLight} />
<mesh geometry={nodes.Sphere015_2.geometry} material={materials.Green} />
<mesh geometry={nodes.Sphere015_3.geometry} material={materials.BrownDark} />

    </group>
  )
}

useGLTF.preload('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/cauldron/model.gltf')

